### ISSUE TITLE
Loosing HTML editor features in cfm page

### ISSUE THREAD

**Issue by snraets** [ilich/vscode-coldfusion#1]
When I start working on a cfm page, I lose the ability to use tab to convert emmet statements.  Is there a fix for this?

Thanks

**Comment by ilich** [comment]
I have never work with emmet before. Could you explain what extensions have you installed? How to use emmet?

**Comment by snraets** [comment]
Visual Studio Code

I will work on an html document.  I can type out div>ul>li then hit "tab".
Visual Studio Code will produce <div><ul><li></li></ul></div>.

I think because it is a cfm page and not html, this feature of using "tab"
no longer works.  cfm pages are losing what we would have in a normal html
page.

Does this make sense?

Thanks

**Comment by ilich** [comment]
I don't think that VS Code support language "inheritance". I am not able to find a way to say that CFML is a child of HTML. Please let me know if you know how to do that.

**Comment by snraets** [comment]
If I find anything, I'll let you know.  Thanks for looking.

**Comment by dariusj18** [comment]
Add this line to your User settings.json file

`"emmet.syntaxProfiles": {
        "lang-cfml": "html"
    }`

This will allow Emmet to work in the CFML Mode

**Comment by cfcoder** [comment]
It appears this has changed in Emmet 2.0. The add line to your User settings.json file should now be:

`"emmet.includeLanguages": {
        "cfml": "html"
    }
`

I found this referenced here: [https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0#_other-changes](url)

**Comment by dariusj18** [comment]
I think it should still be "lang-cfml", the plugin was changed briefly to be "cfml", but then reverted back to "lang-cfml".

**Comment by cfcoder** [comment]
I am using ColdFusion 2016. The "lang-cfml" setting wouldn't work for me until I changed it to just "cfml".

**Comment by dariusj18** [comment]
This is commit I am referring to, you may not have the most recent version of the extension installed.

https://github.com/ilich/vscode-coldfusion/commit/fc835ec06f946cf3830cbd2245e3a72afdb2adf8

**Comment by cfcoder** [comment]
Turns out I am using the KamasamaK extension for CF. I see in the comments for Ilya's github that he would like to join efforts with KamasamaK so that there is just one extension for CF in VSCode. I'm not sure which extension is better. I see Ilya's has more downloads, fwiw.
