### ISSUE TITLE
Last update causes other extension/s to stop functioning

### ISSUE THREAD

**Issue by chapmandu** [ilich/vscode-coldfusion#13]
I noticed since the last update, the `auto-close-tag` extension ceases to work.

https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag

Just an inconvenience really. If a solution is available, that would be great.

Great work.

**Comment by shakeelosmani** [comment]
Hi chapmandu I had the same problem, then i realized it has got nothing to do with this plugin, the guys from auto-close-tag changed their plugin to default to few languages so it does not work with ColdFusion files and the simple solution is add this to your work space settings

"auto-close-tag.activationOnLanguage": [
        "*"
    ],

**Comment by chapmandu** [comment]
Thanks @shakeelosmani
