### ISSUE TITLE
Language Id

### ISSUE THREAD

**Issue by KamasamaK** [ilich/vscode-coldfusion#15]
Why was the [language id](https://code.visualstudio.com/docs/languages/overview#_language-id) chosen to be `lang-cfml`? It looks like none of the languages VSC ships with have a `lang-` prefix. If no one has any objection, I suggest changing it to just `cfml`.

**Comment by ilich** [comment]
There wasn't any reason for that. I renamed the language ID.  Thanks.

**Comment by chapmandu** [comment]
Please note that this change breaks snippets as vscode now looks for cfml.json rather than the previous lang-cfml.json file.

The solution is to simply find and rename the snippets file.

On Mac, the file is located at ~/Library/Application Support/Code/User/snippets/lang-cfml.json

**Comment by chapmandu** [comment]
Also breaks this extension for the same reason as above

https://marketplace.visualstudio.com/items?itemName=trst.cfml-comment-tags

**Comment by ilich** [comment]
I rolled back the change. Please update to 0.0.10

**Comment by KamasamaK** [comment]
@ilich That extension seems very simple. Would you be willing to have that integrated into this one? Per https://github.com/trstt/cfml-comment-tags/issues/1 the owner of the extension thinks it's a good idea.

**Comment by ilich** [comment]
Unfortunately I do not use ColdFusion at the moment and do not have too much time to keep building the extension. I am happy to accept pull requests. :-)

**Comment by ilich** [comment]
But it seems that language change might be critical. I do not know what other plugins use it.

**Comment by KamasamaK** [comment]
It can be critical. I was actually asking because I'm writing a plugin myself and thought the choice of language id was odd. There's also this less popular project -- https://github.com/sketchpunk/vcode_coldfusion/blob/master/package.json -- that uses a number of different ids.

Regarding if there's any others that rely on that particular id, I cannot find any. There's just those other 2 and a file finder that I can't find the source to and has very few downloads. I think the PR I made would have fixed the issue, but now I guess I should cancel it. The one for snippets is trickier since it's a file made for custom user snippets based on the language id, in which case a source code change wouldn't be sufficient.

Although looking at the commit history, I see a few times that the language ids have changed here.
