### ISSUE TITLE
Mixed Language Support (HTML+CFML)

### ISSUE THREAD

**Issue by Joyrex** [ilich/vscode-coldfusion#17]
I'm not sure if this is something this extension should/can address, but with files being identified as CFML, Intellisense is lost for mixed languages (HTML in CFM files, JS in CFM files, SQL in CFM files, etc.).

I've tried adding the file associations to the VS Code config by associating *.cfm as html, but that breaks the syntax highlighting this extension provides. 

Sublime Text seems to know the files are mixed and handles hinting and autocomplete fine - but Visual Studio Code is far more stable in my experience and better supported.

Is this something that this extension can address, or is there a way to configure VS Code to support this?

**Comment by bardware** [comment]
Mix of CFML and SQL is of importance.

**Comment by ilich** [comment]
I've done some research about this. It seems to be doable using grammar injections. https://github.com/mjbvz/vscode-js-template-string-grammar-injection-example

It seems I will create new CFML/CFScript language rules to support those features.

**Comment by Joyrex** [comment]
@ilich : I don't know if it will help at all, but here's the CFML extension for Sublime Text that supports mixed CFML (CFML+HTML, CFML+CSS, CFML+JS, CFML+SQL): https://github.com/SublimeText/ColdFusion

**Comment by ilich** [comment]
@Joyrex : Do you know any official CFML/CFScript language specification and/or language test kit? I found https://github.com/lucee/Lucee/tree/master/test, but I'd like to have some test cfm's as well. Lucee syntax is a bit different from CFML tags.

**Comment by alorne** [comment]
I too am interested in this. SQL, Java, HTML, and CFML would be great on one page!

**Comment by Joyrex** [comment]
@ilich  - sorry I missed this! Charlie Arehart's CF 411 page has a listing of CFML testing tools:
http://www.cf411.com/cfmlcodetest

**Comment by KrunchMuffin** [comment]
is there no way to adapt this package into VSCode? https://github.com/jcberquist/sublimetext-cfml

**Comment by ilich** [comment]
Unfortunately VS Code does not support Sublime Syntax files that are more advanced than TextMate ones. 

https://github.com/Microsoft/vscode/issues/5408

As I understood, there is no way now to mix languages inside VS Code. I haven't found a way to tell the editor that this code is SQL and that code is CFML. 

I have updated CFML syntax highlighting with the latest version from TextMate bundle yesterday. I hope it will make our life a bit easier.
