### ISSUE TITLE
Code Commenting

### ISSUE THREAD

**Issue by timknight** [ilich/vscode-coldfusion#18]
There never seems to be an instance where the `<!--- --->` CFML block commenting seems to be output even though it's found in the language grammar. Anytime I try to use commenting I always get `//`. Is this something that needs to be enabled another way?

**Comment by timknight** [comment]
I wanted to add a note for clarity. What I'm referring to is when I press `Cmd+/` with a section of the code selected, either a block or a single word.

**Comment by timknight** [comment]
Currently my solution is creating a custom keybinding like this:

```
{
  "key": "cmd+/",
  "command": "editor.action.insertSnippet",
  "args": {
    "snippet": "<!--- $TM_SELECTED_TEXT$0 --->"
  },
  "when": "editorTextFocus && editorLangId == lang-cfml"
}
```

But it would be nice for the language grammar to understand if I'm inside tag-based CFML vs. script-based ColdFusion and then select `//` or `<!--- --->` appropriately.

**Comment by KamasamaK** [comment]
I believe this is related to the [language configuration](https://github.com/ilich/vscode-coldfusion/blob/master/cfscript.configuration.json) and not the grammar. That keyboard shortcut just toggles the line comment for the language and is not explicitly contributed by this extension. I'm not aware of a way to make a keybinding contextual in the way you want. I would just advise having the different comment types as different keybindings.

**Comment by timknight** [comment]
Take the built-in HTML extension for example. On a Mac that's available by going into the executables contents and then going to `Contents\Resources\app\extensions\html`.

The `language-configuration.json` defines the comment block item as `<!-- -->`. However if you look in the syntax folder for `html.json` the pattern definitions that begin on line 302 defines how a comment works between `<script></script>` tags. Could be at least a place to start? Granted I know the CFML package is using Textmate Language packages, but perhaps there's hope that this is technically possible.

**Comment by KamasamaK** [comment]
After some testing, it doesn't appear that the grammar is being used for that. The HTML language server is using CSS and JavaScript as embedded languages and delegating to those languages where appropriate. To test this, you can modify `lineComment` in `/app/extensions/javascript/javascript-language-configuration.json` to be `///` and you will see that is what is now being used instead within `<script>` tags of HTML files.

**Comment by timknight** [comment]
Ah good catch. So then I would wonder, just like JavaScript has `/app/extensions/javascript/javascript-language-configuration.json` and `/app/extensions/javascript/tags-language-configuration.json` which are defined in `package.json` based on criteria, if this might not be possible still with this extension. Having two configurations between cfml and cfscript perhaps.

**Comment by charlesr1971** [comment]
I have also noticed that if you write something like this:

```
<cfquery name="local.qryRecipeAttributes" datasource="#application.datasrc#">
    SELECT *
    FROM table
</cfquery>
```

If you try and comment out some of the SQL, by doing:

- select some SQL
- SHIFT+ALT+A [Windows]

It uses:

```
/**/
```

Comments. 
Surely it should be using: 

```
<!--- --->
```
