### ISSUE TITLE
Symbol information on CFML file

### ISSUE THREAD

**Issue by shakeelosmani** [ilich/vscode-coldfusion#25]
When you hit ctrl+p and type @ other languages in VS Code bring up all the functions in the file. Why the coldfusion extension does not do it? Is it a lot of work to do this? If anyone can guide me I can build it. Thanks

![image](https://user-images.githubusercontent.com/9120484/30387119-92898432-9879-11e7-8e99-1727c3a2e609.png)

**Comment by tdhatcher** [comment]
Take a look here for more details. There has been small discussion about the issue.

https://github.com/ilich/vscode-coldfusion/issues/11

**Comment by shakeelosmani** [comment]
Thanks @tdhatcher . Yes i see, seems like a larger endeavor than I thought. Nevertheless this would be a very important feature when dealing with large util cfcs that has tons of functions.

**Comment by 18thAvenue** [comment]
Hi, yes, many people interested in this functionality. For me it's reason I haven't switched to VS code full time. My thought was if you are editing a cfc and switch language to javascript ctrl+p will work. Of course this kills cfml assist. I'm wondering if there is a way for your cfml plugin to just tell VS to use the Javascript symbols file? I don't even care initially if it doesn't work for tag based files. It's a lifesaver in script cfc's. Thank you for the plugin BTW.
