### ISSUE TITLE
Snippets add every single attribute - is there a way to turn that off?

### ISSUE THREAD

**Issue by WebVeteran** [ilich/vscode-coldfusion#27]
For example I type `cfin` and select `cfinput`, I get the kitchen sink: `<cfinput name = "" type = "[ ]" label = "[ ]" style = "[ ]" required = "[ ]" mask = "[ ]" validate = "[ ]" validateAt= "[ ]" message = "[ ]" range = "[ ]" maxlength = "[ ]" pattern = "[ ]" onValidate = "[ ]" onError = "[ ]" size = "[ ]" value = "[ ]" bind = "[ ]" checked = "[ ]" disabled = "[ ]" src = "[ ]" onKeyUp = "[ ]" onKeyDown = "[ ]" onMouseUp = "[ ]" onMouseDown = "[ ]" onChange = "[ ]" onClick = "[ ]" firstDayOfWeek = "[ ]" dayNames = "[ ]" monthNames = "[ ]" enabled = "[ ]" visible = "[ ]" toolTip = "[ ]" height = "[ ]" width = "[ ]">`.
This is a mess. Can it work more like the built in HTML language? When I type `im` and select `img`, I get a very manageable `<img src="" alt="">`. And all the other attributes are suggested as I start typing them.

**Comment by pmolaro** [comment]
+1 for this update.  I've stopped using the snippets because of this.

**Comment by ilich** [comment]
I have updated snippets. They will be release within 1.0.0 release.
