### ISSUE TITLE
Support for Command Forward-Slash for Comments 

### ISSUE THREAD

**Issue by pmolaro** [ilich/vscode-coldfusion#31]
Is it possible to add support for VS Code's cmd-/ that adds comments?  If I'm in a CFML file it should wrap the selected block in `<!--- --->`, and if I'm in a cfscript block it should wrap them in `/* */`.

Current when I try this command in a CMFL file I get the error: Unexpected exception while executing command.

**Comment by ilich** [comment]
Added line comment support in #18
