### ISSUE TITLE
Script components not highlighting in 1.0.0

### ISSUE THREAD

**Issue by sethstone** [ilich/vscode-coldfusion#36]
My vscode auto-updated the coldfusion extension to 1.0.0 and it appears to have broken syntax highlighting on script-based CFCs.  In any given CFC the majority of the file is just white text and occasionally a function call or something might be colorized.  I've tried several syntactically correct CFCs in different projects.  

Also, I followed the instructions here to downgrade to the previous version (0.0.11) and the highlighting was restored: https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/

Please let me know if I can provide more information to help with this issue.  I'm running VSCode 1.19.1 on Windows 10

**Comment by ilich** [comment]
The issue has been fixed. Please install v.1.0.1. Thank you for your help!
