### ISSUE TITLE
No auto closing pairs! Please add!

### ISSUE THREAD

**Issue by mashaHD** [ilich/vscode-coldfusion#4]
Looks like the package is missing auto closures:
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/language-configuration.json

**Comment by mashaHD** [comment]
Thank you for adding that! I am trying to update my extension but it doesn't seem to make a difference. I have even uninstalled it and reinstalled, still no closing quotes. Am I missing something?

**Comment by ilich** [comment]
I haven't pushed it to Visual Studio marketplace yet. You can install it manually for now. https://code.visualstudio.com/Docs/extensions/install-extension

**Comment by mashaHD** [comment]
Awesome! Got it! Thank you!!! :)

**Comment by ilich** [comment]
I've pushed the updates to Visual Studio Marketplace

**Comment by randy-johnson** [comment]
Is the autoclose supposed to work just like it does in sublime or no?  I for the life of me cannot get any tags to autoclose.

**Comment by ilich** [comment]
I don't think it works for autoclose. It works only for special characters: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/language-configuration.json

**Comment by randy-johnson** [comment]
ok thank you.
