### ISSUE TITLE
Nested syntax comments

### ISSUE THREAD

**Issue by dariusj18** [ilich/vscode-coldfusion#8]
What would it take for vscode to know when to use different comments.

Currently this extension uses the cfscript comments everywhere, but it would be good to have tha ability to use 

- Coldfusion comments when in cfml
- Javascript comments in script tags
- CSS comments in styles
- Maybe SQL comments in cfquery
- cfscript comments in cfscript or script based cfc

**Comment by jacobbp25** [comment]
The KB shortcuts writedump/cfdump and abort/cfabort are the reason I'm still using sublime.  Comments pose a very similar cursor context problem.

**Comment by ilich** [comment]
The extension is just a wrappert for tmLanguage file which is open source. Do you know better/more recent cfml.tmLanguage? I can add it into the extension. I am not original tmLanguage developer. :-)
